name: Check for new DuckDB release

on:
  push:
    branches:
      - duckdb-release-bot
  schedule:
    - cron: "0 7 * * *" # runs daily at 07:00 UTC
  workflow_dispatch:

jobs:
  check-duckdb-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run release checker
        env:
          GH_PAT: ${{ secrets.PAT_CREATE_ISSUES }}
        run: python .github/scripts/check_release.py